### ISSUE TITLE
Topic modeling av det politiska i Jupyter I: Skapa topic modeller och topics toppord

### ISSUE THREAD

**Issue by fredrik1984** [humlab/welfare_state_analytics#27]
Gör det möjligt för forskarna i Westac att göra topic modeling på tidningsdatat. Det ska gå att välja antal topics och vilken tidsperiod som det ska göras på (mellan 1945 och 1989). Även om vi utgår från Mallets standardimplementation vill vi förmodligen också laborera med alpha och beta, framförallt beta. 

Det ska också gå att välja hur många toppord som man vill synliggöra i resultatet. Vi vill också att viken för varje topics synliggörs i output datat (typ topic-id+topic-vikt+toppord). Det ska gå att få ut denna lista med topics och toppord som en txt- eller excel-fil.

**Comment by roger-mahler** [comment]
Unfortunately it takes some time to compute the LDA topic models. A 50 topic LDA has an execution time of about 10 hours, a 75 topics computation not yet completed has been running for 18 hours using a multi-core LDA version (8 cores, a Gensim multi-core implementation of LDA).

**Comment by roger-mahler** [comment]
Due to the long execution times it's not feasible to manage LDA executions via the Jupyter pages. Instead the script [lda_runner_gensim](https://github.com/humlab/welfare_state_analytics/blob/master/westac/notebooks/political_in_newspapers/lda_runner_gensim.py) can be used  Currently, without further data preparations, the following topic modelling implementations can be used:

[Gensim LDA](https://radimrehurek.com/gensim/models/ldamodel.html) **tested**
[Gensim LDA MultiCore](https://radimrehurek.com/gensim/models/ldamulticore.html) **tested**
[scikit Learn LDA](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.LatentDirichletAllocation.html#sklearn.decomposition.LatentDirichletAllocation) **tested**

Each method can be configures as described in the API documentation.

[Gensim NMF](https://radimrehurek.com/gensim/models/nmf.html)
[Gensim HDP](https://radimrehurek.com/gensim/models/hdpmodel.html)
[Gensim LSI](https://radimrehurek.com/gensim/models/lsimodel.html)
[Gensim DTM](https://radimrehurek.com/gensim/models/ldaseqmodel.html)
[scikit Learn NMF](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.NMF.html#sklearn.decomposition.NMF)
[scikit Learn LSA](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html#sklearn.decomposition.TruncatedSVD)

### The following small text topic models are partly implemented
[STTM](https://github.com/qiang2100/STTM)   LDA
STTM   BTM
STTM   PTM
STTM  SATM
STTM   DMM
STTM  WATM

**Comment by roger-mahler** [comment]
How to run the batch script:

```bash
pipenv shell
python lda_runner_gensim.py name-of-model --n-topics n [ other-options]
```
Example:
```bash
pipenv shell
python lda_runner_gensim.py lda.50.topics --n-topics 50
```
The project source code needs to be cloned and installed prior to execution.  Note that `git`, `pipenv ` and python 3.6+ needs to be installed on the system as a prerequisites.

```bash
$ mkdir -p ~/source
$ cd ~/source
$ git clone https://github.com/humlab/welfare_state_analytics.git
$ cd welfare_state_analytics
$ pipenv install
````
