### ISSUE TITLE
Topic modeling av det politiska i Jupyter II: Följa topics över tid

### ISSUE THREAD

**Issue by fredrik1984** [humlab/welfare_state_analytics#28]
Eftersom vi har metadata för tid till varje dokument så vill vi kunna välja vilka topics som vi vill följa över tid, som en graf med en linje som representerar ett topics frekvens över tid. Det vore bra om man också kan se topporden för de topics som man väljer att följa över tid.

**Comment by roger-mahler** [comment]
This feature is implemented in notebook '3_explore_topic_models', sections **Topic Trends over Time** and **Topic Trend Overview** similar to notebooks used in Daedalus. Pivoting the data over documents is disabled due to the large number of documents. Furthermore, a new option to filter the data based on publisher is added.
